spring:
  application:
    name: todo-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:3333
  cloud:
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: http://localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key-store:
    location: file:///C:/keyStore/apiEncryptionKey.jks
    alias: apiencryptionkey
    password: cgs2760
